Add support in AnalyzerTest to include source generators as part of the test run
dotnet/roslyn-sdk pull request #1039
Opened 2022-11-10 18:57 UTC by kzu

Implements `CompilationTransforms` so that test authors can provide additional transforms after the basic compilation has been created.

Closes #1038

2022-11-11 19:03 UTC, jmarolf commented
@kzu thanks!, I'll take a look

2022-11-15 22:36 UTC, sharwell requested changes
I believe it would be better to do the following:

1. Update the implementation derived from `AnalyzerTest` in your project to have a `SourceGenerators` property
2. Override `GetProjectCompilationAsync` to apply the source generators before returning, similar to how the [source generator](https://github.com/dotnet/roslyn-sdk/blob/ba5f8a6bf7b477b44a43ea943d3e831d6301afb7/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.SourceGenerators.Testing/SourceGeneratorTest%601.cs#L50-L54) test framework does it

I'll look into updating the test framework to support this approach directly.

2022-11-16 14:59 UTC, sharwell commented
@kzu The framework was designed with inheritance in mind, which is why the project templates default to creating the derived types. Note that you don't need to create a large number of derived types; it's generally sufficient to create one derived type that is used to correctly configure the test framework for all the common test cases in your library.

2022-11-27 21:18 UTC, kzu commented
BTW, the SourceGenerators testing library does not support incremental source generators, so this is even more pressing that might otherwise seem....

2022-11-28 14:33 UTC, sharwell commented
@kzu Incremental source generators are supported by updating the local derived verifier instance, like this:

https://github.com/microsoft/vs-extension-testing/tree/main/src/Microsoft.VisualStudio.Extensibility.Testing.SourceGenerator.UnitTests/Verifiers

I'm going to go ahead and close this PR since we're interested in the feature, but will need a significant rewrite to deliver it. The tracking feature request issues should still be open.

2022-11-28 14:33 UTC, closed without merging

2022-11-28 14:44 UTC, kzu commented
There's a constraint in the test class that only includes ISourceGenerator, not IIncrementalGenerator: https://github.com/dotnet/roslyn-sdk/blob/main/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing/CSharpSourceGeneratorTest%602.cs#L13

Unless you're saying (indirectly) that the  test-derived classes shouldn't be used at all for incremental generator tests?

2022-11-28 14:58 UTC, sharwell commented
The example verifier I linked is constrained to `IIncrementalGenerator`.

2022-12-12 15:02 UTC, sharwell commented
I believe that is already answered above. It would be better if the library supported source generators in the analyzer layer, but so far we haven't had the time to deliver it. Whenever we do deliver this feature, it will follow the common patterns in this library that encourage the use of inheritance to customize the behavior within the context of a downstream test project.