Add color picker for syntax classification
dotnet/roslyn-sdk pull request #620
Opened 2020-09-04 23:47 UTC by ryzngard

Syntax classification and the settings for it aren't really easy to find in Tools > Options > Fonts and Colors. This introduces an easier way to set colors by following the syntax tree. If a TextSpan is classified (using our public API for classification) then we use it to get the VS color settings for that classification and display to the user, allowing it to be changed. 

Most of the code changes are adding a color picker since I couldn't find one in VS or WPF readily. Heavily motivated from https://github.com/dsafa/wpf-color-picker 

Fonts and colors settings ported with help from @JoeRobich 

# Blue Theme Example

![classification_blue_mode](https://user-images.githubusercontent.com/475144/92291537-13bc4280-eece-11ea-97b5-154ad748a822.gif)

# Dark Theme Example

![classification_dark_mode](https://user-images.githubusercontent.com/475144/92291486-c5a73f00-eecd-11ea-802d-a49ae05048ab.gif)

2020-09-05 00:28 UTC, JoeRobich approved these changes
lgtm. just some stale comments

2020-09-05 00:28 UTC, JoeRobich commented on src/VisualStudio.Roslyn.SDK/SyntaxVisualizer/Roslyn.SyntaxVisualizer.Control/FontsAndColorsHelper.cs
> +                // matches the color scheme color.
This comment can be removed.

2020-09-05 00:28 UTC, JoeRobich commented on src/VisualStudio.Roslyn.SDK/SyntaxVisualizer/Roslyn.SyntaxVisualizer.Control/FontsAndColorsHelper.cs
> +            // Open Text Editor category for readonly access.
This comment needs updating.

2020-09-06 15:50 UTC, sharwell commented on src/VisualStudio.Roslyn.SDK/SyntaxVisualizer/Roslyn.SyntaxVisualizer.Control/Roslyn.SyntaxVisualizer.Control.csproj
> +    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="3.3.1" />
```suggestion
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="$(MicrosoftCodeAnalysisWorkspacesCommonVersionVS2019)" />
```

2020-09-06 15:52 UTC, sharwell requested changes
Marking Request Changes so we have an opportunity to verify two things:

1. Does the new dialog need to itself be dark-themed when the dark theme is enabled?
2. What is the accessibility state and story?

2020-09-08 21:25 UTC, ryzngard commented
@sharwell  good call on themeing. I updated the UI to be themed and updated the gifs in the summary. Accessibility I'm following up on with the accessibility champ

2020-09-21 23:11 UTC, ryzngard commented
Merging. @sharwell  this has undergone initial accessibility testing and UX review. There may be additions to the UI in a further review, but this has passed.  Will do a manual test pass with team after checkin per Abhitej's request

2020-09-22 00:07 UTC, merged